engines/web/config/routes.rb
=begin
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=end

Web::Engine.routes.draw do
  root "static_pages#index"
  get "/ebooks", to: "static_pages#ebooks", as: "ebooks"
  scope "/about", as: "about" do
    get "/", to: "static_pages#about"
    get "/our-goals", to: "static_pages#about_our_goals", as: "our_goals"
    get "/exposure", to: "static_pages#about_exposure", as: "exposure"
    get "/dual-license", to: "static_pages#about_dual_license", as: "dual_license"
    get "/accessibility", to: "static_pages#accessibility", as: "accessibility"
  end
  get "/newsletter", to: "static_pages#newsletter", as: "newsletter"
  get "/contribute", to: "static_pages#contribute", as: "contribute"
end

engines/web/app/models/web/application_record.rb
=begin
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=end

module Web
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

engines/web/app/controllers/web/application_controller.rb
=begin
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=end

module Web
  class ApplicationController < ActionController::Base
  end
end

engines/web/app/controllers/web/static_pages_controller.rb
=begin
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=end

module Web
  class StaticPagesController < ApplicationController
  end
end

engines/web/app/helpers/web/application_helper.rb
=begin
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=end

module Web
  module ApplicationHelper
    def public_domain_year
      Time.zone.now.year - 96
    end

    def pdm_logotype(domain = false)
      if domain
        content_tag(:b, class: "logotype") do
          concat content_tag(:svg, content_tag(:use, nil, href: "#pdm-icon"), class: "icon", width: "1.422em", height: "1em")
          concat content_tag(:span, "Public", class: "public")
          concat "&#8203;".html_safe
          concat content_tag(:span, "Domain", class: "domain")
          concat "&#8203;".html_safe
          concat content_tag(:span, "Magic",  class: "magic")
          concat "&#8203;".html_safe
          concat content_tag(:span, ".org",   class: "tld")
        end
      else
        content_tag(:b, class: "logotype") do
          concat content_tag(:svg, content_tag(:use, nil, href: "#pdm-icon"), class: "icon", width: "1.422em", height: "1em")
          concat content_tag(:span, "Public", class: "public")
          concat content_tag(:span, " ",      class: "space")
          concat content_tag(:span, "Domain", class: "domain")
          concat content_tag(:span, " ",      class: "space")
          concat content_tag(:span, "Magic",  class: "magic")
        end
      end
    end
  end
end

engines/web/app/helpers/web/static_pages_helper.rb
=begin
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
=end

module Web
  module StaticPagesHelper
  end
end

engines/web/app/views/web/static_pages/about.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, raw("About #{pdm_logotype}") %>

<p><%= pdm_logotype %> is a volunteer-driven project that catalogs books about magic and the allied arts, researches their <abbr title="United States">U.S.</abbr> copyright status, and produces new editions of public domain ebooks that are lovingly formatted and free of cost.</p>

<h3>More Information</h3>

<ul>
  <li>
    <%= link_to about_our_goals_path do %>
      <%= pdm_logotype %>’s goals, and what we do to achieve them
    <% end %>
  </li>
  <li>
    <%= link_to about_exposure_path do %>
    On whether <%= pdm_logotype %>’s efforts qualify as exposure to the public
    <% end %>
  </li>
</ul>

engines/web/app/views/web/static_pages/about_dual_license.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, "Dual License for our Ebooks" %>

<h2>For Readers</h2>
<p><%= pdm_logotype %> ebooks are available under a <a href="https://en.wikipedia.org/wiki/Dual_licensing">dual licensing</a> model.</p>
<ul>
  <li>We agree with <a href="https://www.gutenberg.org/help/no_sweat_copyright.html">Project Gutenberg&rsquo;s opinion that <q>Work performed on a public domain item, known as &lsquo;sweat of the brow,&rsquo; does not result in a new copyright</q> in the United States</a>. If that is true, <%= pdm_logotype %> ebooks are in the public domain by definition.</li>
  <li>However, if you believe the conversion to a digital form creates a new copyright, or if applicable law recognizes <a href="https://en.wikipedia.org/wiki/Sweat_of_the_brow">&ldquo;sweat of the brow&rdquo;</a> or similar rights, you may use <%= pdm_logotype %> ebooks <strong>only</strong> under the terms of the <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en">CC BY-NC-ND 4.0 license</a>, which prohibits commercial use and distributing modified versions.</li>
</ul>
<p>Either way, you are free to download, read, copy, and print <%= pdm_logotype %> ebooks for no charge.</p>

<h2>For Distributors</h2>
<p>In addition to the terms for readers above, the following apply to those that believe the conversion to a digital form creates a new copyright who would distribute <%= pdm_logotype %> ebooks.</p>
<ul>
  <li>The terms of the <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en">CC BY-NC-ND 4.0 license</a> do not allow use for <a href="https://creativecommons.org/licenses/by-nc-nd/4.0/deed.en#ref-commercial-purposes">commercial purposes</a>.</li>
  <li>By distributing <%= pdm_logotype %> ebooks, you agree not to assert copyright or related rights over digitization or other &ldquo;sweat of the brow&rdquo; labor on <em>any</em> public domain works.</li>
</ul>

<h2>For Contributors, Volunteers, and Producers</h2>
<p><%= pdm_logotype %> only accepts contributions from volunteers who agree that <a href="https://www.gutenberg.org/help/no_sweat_copyright.html">&ldquo;sweat of the brow&rdquo;</a> does <em>not</em> create a new copyright in public domain works. All contributions must be released under the <a href="https://creativecommons.org/publicdomain/zero/1.0/">CC0 1.0 Universal Public Domain Dedication</a>.</p>

engines/web/app/views/web/static_pages/about_exposure.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, "On Exposure" %>

<p>
  <%= pdm_logotype %> opposes <q>the willful exposure to the public of any principles of the Art of Magic or the method employed in any magic effect or illusion.</q> (<cite><a href="https://www.magician.org/pdf/JointIBMAndSamEthics.pdf">Joint <abbr title="International Brotherhood of Magicians">I.B.M.</abbr> and <abbr title="Society of American Magicians">S.A.M.</abbr> Ethics Statement</a></cite>).
  <%# To this end, we protect our downloads with a password that should only allow students, practitioners, and researchers of magic and the allied arts to download our ebooks from our website. %>
</p>
<p><%= pdm_logotype %> does not believe that our efforts constitute exposure. <a href="https://www.p-e-a.org/exposure.pdf">As defined</a> by the <a href="https://www.p-e-a.org">Psychic Entertainers Association</a>, &ldquo;exposure&rdquo; cannot be used to describe magic sections of libraries. <a href="https://archive.org">Internet Archive</a> and <a href="https://www.gutenberg.org">Project Gutenberg</a> are widely recognized as digital libraries, and <%= pdm_logotype :domain %> counts itself among them.</p>
<p>Kerrick Long, the founder of <%= pdm_logotype %>, disclosed this preservation and access work on his application to both the <a href="https://www.magicsam.com/default.aspx">Society of American Magicians</a> and the <a href="https://www.magician.org">International Brotherhood of Magicians</a>, making it very clear that he should not be accepted if this was incompatible with the joint ethics statement. He was proud to be accepted by both organizations, and is a member of both <a href="https://www.magician.org/membercheck?ibmid=RXRMYlJ5NUQ2VDd6aGhiNStGZGltQT09"><abbr title="International Brotherhood of Magicians">I.B.M.</abbr></a> and <a href="https://www.magicsam.com/members/public_profile.asp?id=80533142"><abbr title="Society of American Magicians">S.A.M.</abbr></a> today.</p>

engines/web/app/views/web/static_pages/about_our_goals.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, "About Our Goals" %>

<p><%= pdm_logotype %> works to promote a rich magical culture. Specifically, we aim to conduct our efforts to support the goals of <a href="https://www.archives.gov/files/nhprc/annotation/2007/2007-fall.pdf">preservation</a> and <a href="https://dictionary.archivists.org/entry/access.html">access</a>. These two goals are sometimes referred to as our &ldquo;<a href="https://www.federalreserve.gov/faqs/what-economic-goals-does-federal-reserve-seek-to-achieve-through-monetary-policy.htm">dual mandate</a>.&rdquo;</p>

<h2>Preservation</h2>

<h3>Researching Copyright Status</h3>
<p>Copying is preservation&mdash;the only method of preservation for long enough timescales. To widen the range of works we can preserve, we work to gather <a href="https://en.wikipedia.org/wiki/Evidence_of_absence">evidence of abscence</a> of copyright renewal for <abbr title="United States">U.S.</abbr> works old enough to require renewal. We <a href="https://www.gutenberg.org/help/copyright.html#rule-6-failure-of-us-works-to-comply-with-renewal-requirements-prior-to-1964">submit this research to Project Gutenberg for their clearance</a> to ensure we comply with <abbr title="United States">U.S.</abbr> copyright law. This is the effort that enables all our other tactics to meet our preservation and access goals for works published after <%= public_domain_year %>.</p>

<h3>Scanning Books</h3>
<p>Rather than preserving physical copies of works, we <a href="https://dictionary.archivists.org/entry/scan.html">scan</a> them to preserve the information they contain.</p>
<blockquote>
  <p>The third mode of preservation is copying the content to be preserved onto a new medium. Here the focus is not on preservation of the physical object, but rather on preserving the informational or cultural content of the original by making a surrogate from the original. Since ancient times, scribes have preserved documents by copying them, and copies also provide a mechanism for dissemination of content.</p>
  <cite><a href="https://www.archives.gov/files/nhprc/annotation/2007/2007-fall.pdf">
    <abbr title="National Historical Publications and Records Commission">NHPRC</abbr>, “The Four Modes of Preservation,” <i>Annotation</i>, vol. 34, no. 1, pp. 8&ndash;9, Fall 2007.
  </a></cite>
</blockquote>

<h3>Copying</h3>
<p>Once a works is <a href="https://dictionary.archivists.org/entry/digitize.html">digitized</a>, the tenets of <a href="https://dictionary.archivists.org/entry/digital-preservation.html">digital preservation</a> mean that we encourage as many copies as possible, stored by as many people as possible. <a href="https://dictionary.archivists.org/entry/lots-of-copies-keep-stuff.html">Lots of copies keep stuff safe</a>.</p>
<p>We copy others&lsquo;s digitized public domain works, and we provide copies of our digitizations to <a href="https://archive.org">Internet Archive</a>, <a href="https://www.gutenberg.org">Project Gutenberg</a>, <a href="https://en.wikisource.org/wiki/Main_Page">WikiSource</a>, and other digital libraries. We also offer low-resolution versions of our scans for download at no charge for readers, and high-resolution versions of our scans on archival-quality discs for collectors, publishers, and other interested parties.</p>

<h2>Access</h2>

<h3>Transcribing Scans</h3>
<p>Once a work has been digitized by scanning, work is still required to convert it to a format that is easily readable by the most people on the most devices. <%= pdm_logotype %> transcribes scanned works that aren&rsquo;t already available on <a href="https://www.gutenberg.org">Project Gutenberg</a>, whether scanned by <abbr title="Public Domain Magic">PDM</abbr> volunteers or others, into machine-readable formats. These transcriptions have many benefits compared to scans. Readers can adjust the fonts for better legibility, more devices can load the work and show it on a variety of screen sizes, and it can be used with a wider range of accessibility technology such as text-to-speech software.</p>

<h3>Producing Ebooks</h3>
<p>Even a transcribed work may not be a high-quality ebook up to the standards of <%= pdm_logotype %> and the <a href="https://standardebooks.org/manual/">Standard Ebooks Manual of Style</a>, a rigorous and modern style manual. Our volunteers produce a new edition of transcribed works that takes advantage of state-of-the-art ereader and browser technology. Our volunteers take care when developing each and every ebook to ensure they meet a professional-grade and consistent typographical standard. Our ebooks look good.</p>

<h3>Intellectual Access</h3>
<p><%= pdm_logotype %> seeks to improve <a href="https://dictionary.archivists.org/entry/intellectual-access.html">intellectual access</a> to works about magic and the allied arts. Toward that end, we build tools such as our catalog to enable the discovery and use of works previously unknown to members of the community, even those for which we haven’t yet produced high-quality ebooks.</p>

<h3>Free of Cost</h3>
<p><%= pdm_logotype %> provides <a href="https://dictionary.archivists.org/entry/open-access.html">open access</a> ebooks to members of the community. By making costs optional to all readers, we ensure access to the best public domain works even to the young, the poor, the indebted, the unemployed, the working class, and the starving artists among us.</p>

engines/web/app/views/web/static_pages/contribute.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, "Get Involved" %>

<p><%= pdm_logotype %> is a volunteer-driven project, and there’s room for people of all skill levels to contribute.</p>

<p>At the most basic level, anyone can contribute feedback. Day-to-day readers can tell us about errors they spot in our ebooks. People with an eye for typography and a talent for editing can proofread whole ebooks. Technically inclined readers can produce ebooks themselves, or contribute via GitHub. Those familiar with copyright law and bibiliographical research can help determine the copyright status of post-<%= public_domain_year %> works. You can also make a financial contribution or donate a wanted book to help fund continued ebook development.</p>

<p>For all these and more, start by emailing <%= mail_to "librarian@publicdomainmagic.org" %>.</p>

engines/web/app/views/web/static_pages/ebooks.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, "Ebooks" %>

<p><%= pdm_logotype :domain %> is still under construction. If you would like to help us launch the website and publish our first ebooks, please <%= link_to "reach out to get involved", contribute_path %>.</p>

engines/web/app/views/web/static_pages/index.html.erb
<%#
`public_domain_magic`, the PublicDomainMagic.org information system
Copyright (C) 2025  Kerrick Long <me@kerricklong.com>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
%>

<%= content_for :page_title, "Free and liberated ebooks, carefully produced for magicians and allied artists." %>

<p><%= pdm_logotype %> is a volunteer-driven project that catalogs books about magic and the allied arts, researches their <abbr title="United States">U.S.</abbr> copyright status, and produces new editions of public domain ebooks that are lovingly formatted and free of cost.</p>
<p>Our volunteers work with <a href="https://www.gutenberg.org">Project Gutenberg</a> to research, scan, and transcribe books and periodicals to make them available for the widest number of reading devices. Then, <%= pdm_logotype %> takes those ebooks, formats and typesets them using a carefully designed and professional-grade style manual, fully proofreads and corrects them, and then builds them to create a new edition that takes advantage of state-of-the-art ereader and browser technology.</p>
<p><%= pdm_logotype %> editions aren’t just a beautiful addition to your digital library—they're a fantastic source for effects and methods that can amaze your spectators, impress your friends, and improve your shows.</p>

<%= link_to "Browse our catalog of free ebooks", ebooks_path, class: "button" %>

<h2>What makes <%= pdm_logotype %> editions different?</h2>

<h3>Modern & consistent typography</h3>
<p>Other free ebooks don’t put much effort into professional-quality typography: they use "straight" quotes instead of “curly” quotes, they ignore details like em- and en-dashes, and they look more like early-90’s web pages instead of actual books.</p>
<p><%= pdm_logotype %> applies a rigorous and modern style manual when developing each and every ebook to ensure they meet a professional-grade and consistent typographical standard. Our ebooks look good.</p>

<h3>Full proofing with careful corrections</h3>
<p>Transcriptions from other sources are often filled with typos or suffer from issues like inconsistent spelling, missing accent marks, or missing punctuation. Submitting corrections to such sources can be difficult or impossible, so errors are rarely fixed.</p>
<p>At <%= pdm_logotype %>, we do a careful and complete readthrough of each ebook before releasing it, checking it against a scan of the original pages to fix as many typos as possible. Even if we do miss something, our ebooks are stored in the hugely popular Git source control system, allowing anyone to easily submit a correction.</p>

<h3>Rich & detailed metadata</h3>
<p>Our ebooks include complete, well-researched, and consistent metadata, including original, detailed book blurbs and links to encyclopedia sources. Perfect for machine processing or for extra-curious, technically-minded readers.</p>
<p>Our catalog also links to useful resources for erudite magicians, including <a href="https://conjuringarts.org/askalexander/">Ask Alexander</a>, <a href="https://www.conjuringarchive.com">Conjuring Archive</a>, <a href="https://magicref.net/magicbooks/index.htm">The Magic Reference Pages</a>, <a href="https://geniimagazine.com/wiki/index.php?title=Main_Page">MagicPedia</a>, and more.</p>

<h3>State-of-the-art technology</h3>
<p>Each <%= pdm_logotype %> ebook takes full advantage of the latest ereader technology, including: <ul>
  <li>Hyphenation support,</li>
  <li>Popup footnotes,</li>
  <li>High-resolution and scalable vector graphics,</li>
  <li>Ereader-compatible tables of contents,</li>
</ul> and more. One of our goals is to ensure our ebooks stay up-to-date with the best reading experience technology can provide. Just because it’s a classic doesn’t mean it has to use old technology.</p>

<h3>Quality covers and illustrations</h3>
<p>Everyone knows a book is judged by its cover, but most free ebooks leave it to your ereader software to generate a drab default cover.</p>
<p><%= pdm_logotype %> draws from a vast collection of public domain magic art to create attractive, unique, appropriate, and consistent covers for each of our ebooks.</p>
<p>We also take efforts to scan original printings of books and periodicals at high resolution (1200<abbr title="dots per inch">dpi</abbr>) for high-resolution illustration imagery. We then convert those images to scalable vector graphics so they'll look great at any size on any device.</p>

<h3>Clean code & semantic markup</h3>
<p>Strict <a href="https://standardebooks.org/manual/">coding standards from Standard Ebooks</a> allow technologists and ebook producers to use <%= pdm_logotype %> files as reliable, easy to read, and robust bases for their own work—not to mention as models of what well-crafted ebook files look like. Common code patterns are repeated through different ebooks, so the code never surprises you.</p>
<p>Each ebook is also enhanced with careful standards-based semantic markup that opens the gateway for exciting new kinds of machine processing.</p>

<h3>Free, open-source, & public domain</h3>
<p>We use the popular <a href="https://git-scm.com">Git</a> source control system to track each and every change made to our ebooks. Anyone can easily see a history of changes, or contribute their own changes with the click of a mouse.</p>
<p>And while all of the ebooks we feature and the cover art we draw from are already believed to be in the public domain in the <abbr title="United States">U.S.</abbr>, <%= pdm_logotype %> releases all of the work we put in to each ebook under a dual <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons</a> and public domain license. That makes each and every one of our ebook files not just free, but libre too—because the world deserves more unrestricted culture.</p>
<p>We stand on the shoulders of giants. Our deepest gratitude goes out to the authors, magicians, performers, and historians who created the works we build upon. Our sincerest thanks go out to the volunteers working on modern efforts like <a href="https://standardebooks.org">Standard Ebooks</a>, <a href="https://www.gutenberg.org">Project Gutenberg</a>, <a href="https://www.hathitrust.org">HathiTrust</a>, <a href="https://www.loc.gov">Library of Congress</a>, <a href="https://archive.org">Internet Archive</a>, <a href="https://en.wikisource.org/wiki/Main_Page">WikiSource</a>, the <a href="https://www.w3.org">W3C</a>, and many <a href="https://www.gnu.org/philosophy/free-sw.html"><abbr title="Free/Libre and Open Source Software">F/LOSS</a></a> software projects.</p>